easy_admin:
  entities:
    Product:

      list:
        fields:
          - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

      form:
        fields:
          - { property: 'imageFile', type: 'vich_image' }

      show:
        fields:
          - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

      design:
        form_theme:
          - '@EasyAdmin/form/bootstrap_4.html.twig'
          - '@VichUploader/Form/fields.html.twig'
