vich_uploader:
    db_driver: orm

    mappings:
        products_image:
            uri_prefix: '%products_image%'
            upload_destination: '%kernel.project_dir%/public%products_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
